/**
 * Phase coin issuance API — sovereign in-house minting.
 *
 * Flow: draft -> (digitally sign issuer agreement | declare meme coin) -> mint.
 * Minting provisions a dedicated sovereign chain per coin via
 * ./sovereign-ledger-core.js (each coin gets its own isolated chain —
 * that is the moat). There is no Solana/mainnet code path.
 *
 * Persistence: Postgres when DATABASE_URL is set, otherwise an in-memory
 * store (dev/test). The store interface is identical in both modes.
 *
 * Mounted from phase-backend.ts: mountIssuanceRoutes({ route, sendJson, HttpError })
 */
import { createHash, randomUUID } from "node:crypto";
import { createChain, LedgerError } from "./sovereign-ledger-core.js";
import { getPool } from "./db.js";

// ---------------------------------------------------------------------------
// Canonical issuer agreement text.
// Mirrors workspace/phase-android/public/docs/phase-issuer-agreement.pdf
// ("PHASE ISSUER AGREEMENT — Template") in meaning; placeholders are filled
// from the draft at render time. The sha256 of the RENDERED text is what the
// signature record stores.
// ---------------------------------------------------------------------------

const TEMPLATE_ONLY_NOTICE =
  "TEMPLATE ONLY — NOT LEGAL ADVICE. This document is a template generated automatically " +
  "from information the Issuer provided. It is for demonstration purposes, is not a binding " +
  "legal agreement as generated, and is not a substitute for independent legal advice. Issuer " +
  "and Phase should have legal counsel review and finalize this agreement before relying on " +
  "it for any live offering.";

export interface IssuanceDraftInput {
  userId: string;
  name: string;
  ticker: string;
  category?: string;
  tagline?: string;
  valueThesis?: string;
  equityPublic?: number;
  equityRetained?: number;
  socialProfiles?: Array<{ platform: string; url: string }>;
  priceUsd?: number; // issuer's starting price per whole coin, USD
}

export interface IssuanceDraft extends Required<Omit<IssuanceDraftInput, "category" | "tagline" | "valueThesis" | "equityPublic" | "equityRetained" | "socialProfiles" | "priceUsd">> {
  id: string;
  category: string;
  tagline: string;
  valueThesis: string;
  equityPublic: number;
  equityRetained: number;
  socialProfiles: Array<{ platform: string; url: string }>;
  priceUsd: number; // issuer's starting price per whole coin, USD
  status: "draft" | "signed" | "minted";
  createdAt: string;
  updatedAt: string;
}

export interface IssuanceSignature {
  id: string;
  draftId: string;
  userId: string;
  legalName: string;
  agreementHash: string;
  agreementText: string;
  signedAt: string;
}

export interface IssuanceCoin {
  id: string;
  draftId: string;
  userId: string;
  signatureId: string | null;
  isMeme: boolean;
  name: string;
  ticker: string;
  mintAddress: string;
  txSignature: string;
  supply: string;
  decimals: number;
  priceUsd: number; // issuer's starting price per whole coin, USD (trade price)
  network: "sovereign";
  idempotencyKey: string;
  createdAt: string;
}

/** Render the agreement for a draft: blanks filled, ready to sign. */
export function renderAgreementText(d: IssuanceDraft): string {
  return [
    "PHASE ISSUER AGREEMENT",
    "Template — generated by Phase Platforms",
    "",
    `This Issuer Agreement ("Agreement") is made by the undersigned issuer ("Issuer") for the benefit of each`,
    `person who purchases shares of the coin described below (each, a "Purchaser").`,
    "",
    "1. The Coin",
    `Issuer is listing "${d.name}" (${d.ticker}) (the "Coin") on the Phase network. Issuer describes the`,
    `basis of the Coin's value as follows:`,
    `"${d.valueThesis || "—"}" (the "Value Thesis").`,
    "",
    "2. Share Split",
    `At genesis, 1,000,000 shares of the Coin are minted: ${d.equityPublic}% allocated to the public float and`,
    `${d.equityRetained}% retained by Issuer (the "Sovereign Split").`,
    "",
    "3. Issuer Representations",
    "Issuer represents and warrants to each Purchaser that:",
    " (a) Identity & Authority. Issuer is the person or business named below and has full authority to enter",
    "into this Agreement and to tokenize and offer the described value.",
    "(b) Accuracy. All information Issuer provided about the Coin — including identity, audience,",
    "financial, and business information — is true and complete to Issuer's knowledge, with no material",
    "fact omitted and no misleading statement.",
    "(c) Rights. Tokenizing and offering the described value does not infringe the intellectual-property,",
    "publicity, or other rights of any third party.",
    "(d) Compliance. Issuer will comply with all applicable laws and regulations in connection with the",
    "Coin.",
    "",
    "4. Value Sharing",
    "Issuer intends that any future income, appreciation, royalties, or other economic value generated by the",
    "activity or asset described for this Coin will be reflected in the Coin's share price, in proportion to the",
    "Sovereign Split, for as long as shares remain publicly held.",
    "",
    "5. Purchaser Acknowledgments",
    "Each Purchaser acknowledges that:",
    " (i) no return is guaranteed and the Coin's value may decline, including to zero;",
    "(ii) the Coin trades on an isolated ledger whose price moves independently of any other chain or asset",
    "on the Phase network;",
    "(iii) this is a prototype market and the Coin is a demonstration instrument unless and until offered",
    "under applicable law with appropriate disclosures.",
    "",
    "6. Term",
    "This Agreement remains in effect for as long as any shares of the Coin are publicly held.",
    "",
    "7. Governing Terms",
    "This Agreement incorporates Phase's Onchaining Terms & Consent by reference. In the event of conflict,",
    "this Agreement controls as between Issuer and Purchasers.",
    "",
    "Signatures",
    "Issuer legal name (print): ________________________________________",
    "Signature: ________________________________________",
    "By typing their full name in the Phase app, Issuer signs this Agreement electronically.",
    "Date: ____________________",
    "",
    TEMPLATE_ONLY_NOTICE,
  ].join("\n");
}

export function sha256Hex(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}

// ---------------------------------------------------------------------------
// Store: Postgres when DATABASE_URL is set, in-memory fallback otherwise.
// ---------------------------------------------------------------------------

export interface IssuanceStore {
  ensureUser(userId: string, email?: string): Promise<void>;
  createDraft(d: Omit<IssuanceDraft, "id" | "status" | "createdAt" | "updatedAt">): Promise<IssuanceDraft>;
  getDraft(id: string): Promise<IssuanceDraft | null>;
  setDraftStatus(id: string, status: IssuanceDraft["status"]): Promise<void>;
  storeSignature(s: Omit<IssuanceSignature, "id" | "signedAt">): Promise<IssuanceSignature>;
  getSignatureByDraft(draftId: string): Promise<IssuanceSignature | null>;
  getCoinByIdempotency(key: string): Promise<IssuanceCoin | null>;
  getCoinByDraft(draftId: string): Promise<IssuanceCoin | null>;
  getCoinByChainId(chainId: string): Promise<IssuanceCoin | null>;
  storeCoin(c: Omit<IssuanceCoin, "id" | "createdAt" | "network">): Promise<IssuanceCoin>;
  listCoinsByUser(userId: string): Promise<IssuanceCoin[]>;
}

class PgIssuanceStore implements IssuanceStore {
  private async q<T>(text: string, params: unknown[] = []): Promise<T[]> {
    const r = await getPool().query(text, params as unknown[]);
    return r.rows as T[];
  }

  async ensureUser(userId: string, email?: string): Promise<void> {
    await this.q(
      `INSERT INTO issuance_users(id, email) VALUES ($1, $2)
       ON CONFLICT (id) DO UPDATE SET email = COALESCE(EXCLUDED.email, issuance_users.email)`,
      [userId, email ?? null]
    );
  }

  async createDraft(d: Omit<IssuanceDraft, "id" | "status" | "createdAt" | "updatedAt">): Promise<IssuanceDraft> {
    const id = randomUUID();
    const rows = await this.q<IssuanceDraft>(
      `INSERT INTO issuance_drafts
         (id, user_id, name, ticker, category, tagline, value_thesis, equity_public,
          equity_retained, social_profiles, price_usd, status)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'draft')
       RETURNING id, user_id AS "userId", name, ticker, category, tagline,
                 value_thesis AS "valueThesis", equity_public AS "equityPublic",
                 equity_retained AS "equityRetained",
                 social_profiles AS "socialProfiles", price_usd AS "priceUsd",
                 status,
                 created_at AS "createdAt", updated_at AS "updatedAt"`,
      [id, d.userId, d.name, d.ticker, d.category, d.tagline, d.valueThesis,
       d.equityPublic, d.equityRetained, JSON.stringify(d.socialProfiles), d.priceUsd]
    );
    return rows[0]!;
  }

  async getDraft(id: string): Promise<IssuanceDraft | null> {
    const rows = await this.q<IssuanceDraft>(
      `SELECT id, user_id AS "userId", name, ticker, category, tagline,
              value_thesis AS "valueThesis", equity_public AS "equityPublic",
              equity_retained AS "equityRetained",
              social_profiles AS "socialProfiles", price_usd AS "priceUsd",
              status,
              created_at AS "createdAt", updated_at AS "updatedAt"
       FROM issuance_drafts WHERE id = $1`,
      [id]
    );
    return rows[0] ?? null;
  }

  async setDraftStatus(id: string, status: IssuanceDraft["status"]): Promise<void> {
    await this.q(`UPDATE issuance_drafts SET status = $2, updated_at = now() WHERE id = $1`, [id, status]);
  }

  async storeSignature(s: Omit<IssuanceSignature, "id" | "signedAt">): Promise<IssuanceSignature> {
    const id = randomUUID();
    const rows = await this.q<IssuanceSignature>(
      `INSERT INTO issuance_signatures
         (id, draft_id, user_id, legal_name, agreement_hash, agreement_text)
       VALUES ($1,$2,$3,$4,$5,$6)
       RETURNING id, draft_id AS "draftId", user_id AS "userId",
                 legal_name AS "legalName", agreement_hash AS "agreementHash",
                 agreement_text AS "agreementText", signed_at AS "signedAt"`,
      [id, s.draftId, s.userId, s.legalName, s.agreementHash, s.agreementText]
    );
    return rows[0]!;
  }

  async getSignatureByDraft(draftId: string): Promise<IssuanceSignature | null> {
    const rows = await this.q<IssuanceSignature>(
      `SELECT id, draft_id AS "draftId", user_id AS "userId",
              legal_name AS "legalName", agreement_hash AS "agreementHash",
              agreement_text AS "agreementText", signed_at AS "signedAt"
       FROM issuance_signatures WHERE draft_id = $1`,
      [draftId]
    );
    return rows[0] ?? null;
  }

  async getCoinByIdempotency(key: string): Promise<IssuanceCoin | null> {
    const rows = await this.q<IssuanceCoin>(`SELECT ${COIN_COLS} FROM issuance_coins WHERE idempotency_key = $1`, [key]);
    return rows[0] ?? null;
  }

  async getCoinByDraft(draftId: string): Promise<IssuanceCoin | null> {
    const rows = await this.q<IssuanceCoin>(`SELECT ${COIN_COLS} FROM issuance_coins WHERE draft_id = $1`, [draftId]);
    return rows[0] ?? null;
  }

  async getCoinByChainId(chainId: string): Promise<IssuanceCoin | null> {
    const rows = await this.q<IssuanceCoin>(`SELECT ${COIN_COLS} FROM issuance_coins WHERE mint_address = $1`, [chainId]);
    return rows[0] ?? null;
  }

  async storeCoin(c: Omit<IssuanceCoin, "id" | "createdAt" | "network">): Promise<IssuanceCoin> {
    const id = randomUUID();
    const rows = await this.q<IssuanceCoin>(
      `INSERT INTO issuance_coins
         (id, draft_id, user_id, signature_id, is_meme, name, ticker,
          mint_address, tx_signature, supply, decimals, price_usd, network, idempotency_key)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'sovereign',$13)
       ON CONFLICT (idempotency_key) DO NOTHING
       RETURNING ${COIN_COLS}`,
      [id, c.draftId, c.userId, c.signatureId, c.isMeme, c.name, c.ticker,
       c.mintAddress, c.txSignature, c.supply, c.decimals, c.priceUsd, c.idempotencyKey]
    );
    // Lost the race: another request with the same key already stored a coin.
    const existing = await this.getCoinByIdempotency(c.idempotencyKey);
    if (!existing) throw new Error("idempotency conflict without existing coin");
    return existing;
  }

  async listCoinsByUser(userId: string): Promise<IssuanceCoin[]> {
    return this.q<IssuanceCoin>(
      `SELECT ${COIN_COLS} FROM issuance_coins WHERE user_id = $1 ORDER BY created_at DESC`,
      [userId]
    );
  }
}

const COIN_COLS = `id, draft_id AS "draftId", user_id AS "userId",
  signature_id AS "signatureId", is_meme AS "isMeme", name, ticker,
  mint_address AS "mintAddress", tx_signature AS "txSignature",
  supply, decimals, price_usd AS "priceUsd", network, idempotency_key AS "idempotencyKey",
  created_at AS "createdAt"`;

class MemoryIssuanceStore implements IssuanceStore {
  private users = new Map<string, { email?: string }>();
  private drafts = new Map<string, IssuanceDraft>();
  private sigsByDraft = new Map<string, IssuanceSignature>();
  private coins = new Map<string, IssuanceCoin>();
  private coinsByKey = new Map<string, IssuanceCoin>();

  async ensureUser(userId: string, email?: string): Promise<void> {
    if (!this.users.has(userId)) this.users.set(userId, { email });
  }
  async createDraft(d: Omit<IssuanceDraft, "id" | "status" | "createdAt" | "updatedAt">): Promise<IssuanceDraft> {
    const now = new Date().toISOString();
    const draft: IssuanceDraft = { ...d, id: randomUUID(), status: "draft", createdAt: now, updatedAt: now };
    this.drafts.set(draft.id, draft);
    return draft;
  }
  async getDraft(id: string): Promise<IssuanceDraft | null> {
    return this.drafts.get(id) ?? null;
  }
  async setDraftStatus(id: string, status: IssuanceDraft["status"]): Promise<void> {
    const d = this.drafts.get(id);
    if (d) { d.status = status; d.updatedAt = new Date().toISOString(); }
  }
  async storeSignature(s: Omit<IssuanceSignature, "id" | "signedAt">): Promise<IssuanceSignature> {
    const sig: IssuanceSignature = { ...s, id: randomUUID(), signedAt: new Date().toISOString() };
    this.sigsByDraft.set(s.draftId, sig);
    return sig;
  }
  async getSignatureByDraft(draftId: string): Promise<IssuanceSignature | null> {
    return this.sigsByDraft.get(draftId) ?? null;
  }
  async getCoinByIdempotency(key: string): Promise<IssuanceCoin | null> {
    return this.coinsByKey.get(key) ?? null;
  }
  async getCoinByDraft(draftId: string): Promise<IssuanceCoin | null> {
    for (const c of this.coins.values()) if (c.draftId === draftId) return c;
    return null;
  }
  async getCoinByChainId(chainId: string): Promise<IssuanceCoin | null> {
    for (const c of this.coins.values()) if (c.mintAddress === chainId) return c;
    return null;
  }
  async storeCoin(c: Omit<IssuanceCoin, "id" | "createdAt" | "network">): Promise<IssuanceCoin> {
    const existing = this.coinsByKey.get(c.idempotencyKey);
    if (existing) return existing;
    const coin: IssuanceCoin = { ...c, network: "sovereign", id: randomUUID(), createdAt: new Date().toISOString() };
    this.coins.set(coin.id, coin);
    this.coinsByKey.set(coin.idempotencyKey, coin);
    return coin;
  }
  async listCoinsByUser(userId: string): Promise<IssuanceCoin[]> {
    return [...this.coins.values()].filter((c) => c.userId === userId)
      .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
  }
}

let storeInstance: IssuanceStore | null = null;
let storeMode: "postgres" | "memory" = "memory";

/** Which backing store is active. Useful for /healthz and logs. */
export function issuanceStoreMode(): "postgres" | "memory" {
  void getStore();
  return storeMode;
}

async function pgReachable(): Promise<boolean> {
  try {
    const pool = getPool();
    // Short-lived check: never hang boot on a dead database.
    const client = await pool.connect();
    try {
      await client.query("SELECT 1");
      return true;
    } finally {
      client.release();
    }
  } catch {
    return false;
  }
}

// Resolved once, lazily, on first use (async init guarded by a promise).
let storeInit: Promise<IssuanceStore> | null = null;
function getStoreAsync(): Promise<IssuanceStore> {
  if (!storeInit) {
    storeInit = (async () => {
      if (await pgReachable()) {
        storeMode = "postgres";
        storeInstance = new PgIssuanceStore();
      } else {
        storeMode = "memory";
        console.warn(
          "[issuance] Postgres unreachable — using in-memory store. " +
          "Coins/drafts will NOT survive a restart. Set DATABASE_URL to a live Postgres for durability."
        );
        storeInstance = new MemoryIssuanceStore();
      }
      return storeInstance;
    })();
  }
  return storeInit;
}

function getStore(): IssuanceStore {
  // Synchronous accessor for code paths that already run inside async fns:
  // falls back to memory until the async probe completes, then swaps.
  // In practice every route handler awaits getStoreAsync() via `store()`.
  if (!storeInstance) {
    storeInstance = new MemoryIssuanceStore();
    void getStoreAsync().then((s) => { storeInstance = s; });
  }
  return storeInstance;
}

/** Async store accessor — every route handler must go through this. */
function store(): Promise<IssuanceStore> {
  return getStoreAsync();
}

/** Shared store accessor for sibling modules (marketplace settlement). */
export function getIssuanceStore(): Promise<IssuanceStore> {
  return getStoreAsync();
}

// ---------------------------------------------------------------------------
// Mount
// ---------------------------------------------------------------------------

export interface IssuanceMountDeps {
  // `any` on res/ctx keeps this module decoupled from phase-backend.ts while
  // remaining assignable from its (res: ServerResponse) => void helpers.
  route: (method: string, path: string, handler: (ctx: any) => void | Promise<void>) => void;
  sendJson: (res: any, statusCode: number, body: unknown) => void;
  HttpError: new (statusCode: number, code: string, message: string) => Error;
}

interface IssuanceCtx {
  req: { headers: Record<string, string | string[] | undefined> };
  res: any;
  params: Record<string, string>;
  query: URLSearchParams;
  body: unknown;
}

const NETWORK_ENVELOPE = { network: "sovereign" as const, chain: "phase" as const };

function asRecord(body: unknown): Record<string, unknown> {
  return (body !== null && typeof body === "object" && !Array.isArray(body))
    ? (body as Record<string, unknown>)
    : {};
}

function str(v: unknown): string {
  return typeof v === "string" ? v : "";
}

function validateTicker(raw: string): string {
  const t = raw.trim().toUpperCase();
  if (!/^[A-Z0-9]{2,10}$/.test(t)) {
    throw new IssuanceHttpError(422, "invalid_ticker", "ticker must be 2-10 characters, A-Z and 0-9 only");
  }
  return t;
}

// Local error type so this module works without importing phase-backend.ts.
class IssuanceHttpError extends Error {
  constructor(public statusCode: number, public code: string, message: string) {
    super(message);
  }
}

export function mountIssuanceRoutes(deps: IssuanceMountDeps): void {
  const { route, sendJson } = deps;
  const HttpError = deps.HttpError as unknown as typeof IssuanceHttpError;

  const fail = (ctx: IssuanceCtx, err: unknown): void => {
    const e = err as { statusCode?: number; status?: number; code?: string };
    const statusCode = e.statusCode ?? e.status ?? 500;
    const code = e.code ?? "internal_error";
    const message = err instanceof Error ? err.message : String(err);
    sendJson(ctx.res, statusCode, { ...NETWORK_ENVELOPE, error: code, message });
  };

  const requireUserId = (ctx: IssuanceCtx): string => {
    const body = asRecord(ctx.body);
    const id = str(body.userId) || str(ctx.query.get("userId"));
    if (!id) throw new HttpError(400, "missing_user_id", "Provide userId in the body or query string.");
    return id;
  };

  const idempotencyKey = (ctx: IssuanceCtx): string => {
    const header = ctx.req.headers["idempotency-key"] ?? ctx.req.headers["x-idempotency-key"];
    const h = Array.isArray(header) ? header[0] : header;
    const body = asRecord(ctx.body);
    const key = str(h) || str(body.idempotencyKey);
    if (!key) {
      throw new HttpError(400, "missing_idempotency_key",
        "POST /api/v1/issuance/mint requires an Idempotency-Key header (or idempotencyKey in the body).");
    }
    return key;
  };

  // --- POST /api/v1/issuance/draft ---
  route("POST", "/api/v1/issuance/draft", async (ctx) => {
    try {
      const body = asRecord(ctx.body);
      const userId = requireUserId(ctx);
      const name = str(body.name).trim();
      if (name.length < 1 || name.length > 60) {
        throw new HttpError(422, "invalid_name", "name must be 1-60 characters");
      }
      const ticker = validateTicker(str(body.ticker));
      const equityPublic = body.equityPublic === undefined ? 50 : Number(body.equityPublic);
      const equityRetained = body.equityRetained === undefined ? 50 : Number(body.equityRetained);
      if (![equityPublic, equityRetained].every((n) => Number.isInteger(n) && n >= 0 && n <= 100)
          || equityPublic + equityRetained !== 100) {
        throw new HttpError(422, "invalid_split",
          "equityPublic and equityRetained must be whole numbers 0-100 that sum to 100");
      }
      const socialProfiles = Array.isArray(body.socialProfiles)
        ? (body.socialProfiles as Array<{ platform?: string; url?: string }>)
            .filter((s) => s && typeof s.url === "string" && s.url.trim())
            .map((s) => ({ platform: str(s.platform).trim(), url: str(s.url).trim() }))
        : [];
      const priceUsdRaw = body.priceUsd ?? body.price_usd;
      const priceUsd = priceUsdRaw === undefined ? 10 : Number(priceUsdRaw);
      if (!Number.isFinite(priceUsd) || priceUsd <= 0 || priceUsd > 1_000_000_000) {
        throw new HttpError(422, "invalid_price", "priceUsd must be a positive number.");
      }

      const s = await store();
      await s.ensureUser(userId, str(body.email) || undefined);
      const draft = await s.createDraft({
        userId,
        name,
        ticker,
        category: str(body.category).trim(),
        tagline: str(body.tagline).trim().slice(0, 280),
        valueThesis: str(body.valueThesis ?? body.value_thesis).trim().slice(0, 2000),
        equityPublic,
        equityRetained,
        socialProfiles,
        priceUsd,
      });
      sendJson(ctx.res, 201, { ...NETWORK_ENVELOPE, draftId: draft.id, status: draft.status, draft });
    } catch (err) { fail(ctx, err); }
  });

  // --- GET /api/v1/issuance/agreement?draftId= ---
  route("GET", "/api/v1/issuance/agreement", async (ctx) => {
    try {
      const draftId = str(ctx.query.get("draftId"));
      if (!draftId) throw new HttpError(400, "missing_draft_id", "Query parameter draftId is required.");
      const _st = await store();
      const draft = await _st.getDraft(draftId);
      if (!draft) throw new HttpError(404, "draft_not_found", "No draft with that id.");
      const agreementText = renderAgreementText(draft);
      sendJson(ctx.res, 200, {
        ...NETWORK_ENVELOPE,
        draftId,
        agreementText,
        agreementHash: sha256Hex(agreementText),
        templateNote: TEMPLATE_ONLY_NOTICE,
      });
    } catch (err) { fail(ctx, err); }
  });

  // --- POST /api/v1/issuance/sign ---
  route("POST", "/api/v1/issuance/sign", async (ctx) => {
    try {
      const body = asRecord(ctx.body);
      const userId = requireUserId(ctx);
      const draftId = str(body.draftId);
      if (!draftId) throw new HttpError(400, "missing_draft_id", "Body must include draftId.");
      const legalName = str(body.legalName).trim();
      if (legalName.length < 2) {
        throw new HttpError(422, "invalid_legal_name", "legalName is required: type your full legal name to sign.");
      }
      if (body.accepted !== true) {
        throw new HttpError(422, "not_accepted", "accepted must be true: you must accept the agreement to sign it.");
      }
      const s = await store();
      const draft = await s.getDraft(draftId);
      if (!draft) throw new HttpError(404, "draft_not_found", "No draft with that id.");
      if (draft.userId !== userId) throw new HttpError(403, "forbidden", "This draft belongs to a different user.");
      if (await s.getCoinByDraft(draftId)) {
        throw new HttpError(409, "already_minted", "This draft has already been minted.");
      }
      const agreementText = renderAgreementText(draft);
      const sig = await s.storeSignature({
        draftId,
        userId,
        legalName,
        agreementHash: sha256Hex(agreementText),
        agreementText,
      });
      await s.setDraftStatus(draftId, "signed");
      sendJson(ctx.res, 201, {
        ...NETWORK_ENVELOPE,
        signatureId: sig.id,
        draftId,
        legalName: sig.legalName,
        agreementHash: sig.agreementHash,
        signedAt: sig.signedAt,
      });
    } catch (err) { fail(ctx, err); }
  });

  // --- POST /api/v1/issuance/mint ---
  route("POST", "/api/v1/issuance/mint", async (ctx) => {
    try {
      const body = asRecord(ctx.body);
      const userId = requireUserId(ctx);
      const draftId = str(body.draftId);
      if (!draftId) throw new HttpError(400, "missing_draft_id", "Body must include draftId.");
      const isMeme = body.meme === true;
      const key = idempotencyKey(ctx);

      const s = await store();

      // Idempotent replay: same key -> original coin, no second mint.
      const replay = await s.getCoinByIdempotency(key);
      if (replay) {
        sendJson(ctx.res, 200, { ...NETWORK_ENVELOPE, idempotentReplay: true, coin: replay });
        return;
      }

      const draft = await s.getDraft(draftId);
      if (!draft) throw new HttpError(404, "draft_not_found", "No draft with that id.");
      if (draft.userId !== userId) throw new HttpError(403, "forbidden", "This draft belongs to a different user.");
      if (await s.getCoinByDraft(draftId)) {
        throw new HttpError(409, "already_minted", "This draft has already been minted.");
      }

      let signatureId: string | null = null;
      let agreementHash: string | undefined;
      if (!isMeme) {
        const sig = await s.getSignatureByDraft(draftId);
        if (!sig) {
          throw new HttpError(422, "signature_required",
            "This draft has no signed issuer agreement. Sign it first (POST /api/v1/issuance/sign), or mint as a meme coin with {\"meme\": true}.");
        }
        signatureId = sig.id;
        agreementHash = sig.agreementHash;
      }

      // Provision a dedicated sovereign chain for this coin in-house.
      // Each coin gets its own isolated chain — that is the moat.
      // Throws LedgerError on invalid input -> mapped to 4xx by fail().
      const issuerAddress = str(body.issuerAddress);
      if (!issuerAddress) {
        throw new HttpError(400, "missing_issuer_address",
          "Body must include issuerAddress: your Phase sovereign wallet address (ph1...).");
      }
      const totalSharesRaw = body.totalShares;
      const totalShares = totalSharesRaw === undefined ? 100000 : Number(totalSharesRaw);
      if (!Number.isInteger(totalShares) || totalShares < 1000) {
        throw new HttpError(422, "invalid_total_shares", "totalShares must be a whole number >= 1000.");
      }
      const chain = createChain({
        coin_name: draft.name,
        ticker: draft.ticker,
        total_supply: String(totalShares),
        decimals: 6,
        equity_public_pct: draft.equityPublic,
        issuer_address: issuerAddress,
        is_meme: isMeme,
        issuance_draft_id: draftId,
        issuance_signature_id: signatureId,
        covenant_hash: agreementHash,
      });

      const coin = await s.storeCoin({
        draftId,
        userId,
        signatureId,
        isMeme,
        name: draft.name,
        ticker: draft.ticker,
        mintAddress: chain.chain_id,
        txSignature: chain.genesis_hash,
        supply: String(totalShares),
        decimals: 6,
        priceUsd: draft.priceUsd,
        idempotencyKey: key,
      });
      await s.setDraftStatus(draftId, "minted");

      sendJson(ctx.res, 201, {
        ...NETWORK_ENVELOPE,
        idempotentReplay: false,
        coin,
        chainId: chain.chain_id,
        genesisHash: chain.genesis_hash,
      });
    } catch (err) { fail(ctx, err); }
  });

  // --- GET /api/v1/issuance/coins?userId= ---
  route("GET", "/api/v1/issuance/coins", async (ctx) => {
    try {
      const userId = requireUserId(ctx);
      const _st2 = await store();
      const coins = await _st2.listCoinsByUser(userId);
      sendJson(ctx.res, 200, { ...NETWORK_ENVELOPE, userId, coins });
    } catch (err) { fail(ctx, err); }
  });

  // --- GET /api/v1/issuance/coins/:id ---
  route("GET", "/api/v1/issuance/coins/:id", async (ctx) => {
    try {
      const userId = requireUserId(ctx);
      const _st2 = await store();
      const coins = await _st2.listCoinsByUser(userId);
      const coin = coins.find((c) => c.id === ctx.params.id || c.mintAddress === ctx.params.id);
      if (!coin) throw new HttpError(404, "coin_not_found", "No coin with that id or chain id for this user.");
      sendJson(ctx.res, 200, {
        ...NETWORK_ENVELOPE,
        coin,
        chainId: coin.mintAddress,
      });
    } catch (err) { fail(ctx, err); }
  });
}
